# Generated by Django 4.2.10 on 2024-03-17 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sneaksbid', '0010_shoe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='description',
            new_name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='djstripe_created',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='djstripe_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='djstripe_owner_account',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='djstripe_updated',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='livemode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid',
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
