# Generated by Django 4.2.10 on 2024-03-17 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneaksbid', '0011_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
    ]
