# Generated by Django 4.2.10 on 2024-03-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneaksbid', '0014_remove_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='timestamp',
        ),
    ]
